image: "node:latest"

cache:
  paths:
    - node_modules/

job-publish:
  only:
    - tags

  before_script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

  script:
    - yarn install
    - yarn run build
    - NPM_TOKEN=$(printenv TOKEN) npm publish
